### ISSUE TITLE
Gatling failed. No simulations to run

### ISSUE THREAD

**Issue by scranen** [gatling/gatling-maven#10]
I have a set-up in which gatling is in a submodule, like so:
```
pom.xml
module1
  ├─ pom.xml
  └─ module2
     ├─ pom.xml
     └─ src 
         └─ test
            └─ scala
               └─ ... simulations ...
```
Now when I run `mvn verify` or `mvn gatling:execute` from different locations, I get different results:
- running from `module1/module2` works fine
- running from the root directory results in 
  ```[ERROR] Failed to execute goal io.gatling:gatling-maven-plugin:2.2.0-M2:execute (default) on project my-project: Gatling failed. No simulations to run -> [Help 1]```
- running from the root directory _after_ having run from `module1/module2`, it appears to run fine again

The reason seems to be that the compiled scenario classes are not stored in the right place. When I execute from the root directory, the class files end up in `/target/test-classes` instead of in `module1/module2/target/test-classes`.

I checked the output of `mvn gatling:execute -X`, and that reports the correct location for `compiledClassesFolder` (i.e., it reports `module1/module2/target/test-classes`).

**Comment by slandelle** [comment]
I suspect you're using old versions and that this issue is already fixed.
Please test with Gatling 2.2.0 (we'll release in 1 hour) and report if it still doesn't work.

Then, please use the gatling main project bug tracker.
