### ISSUE TITLE
Missing quotations including system properties contaning spaces in the fork call

### ISSUE THREAD

**Issue by r-alukhanov** [gatling/gatling-maven#7]
Jenkins provides a plenty of information over the system properties. The class `io.gatling.mojo.Fork` reads all of them and adds to JVM arguments as 

`this.jvmArgs.add("-D" + name + "=" + StringUtils.escape(value));`

If the property value contains spaces (which happens often on Windows platform), it breaks the fork call. Very possible error message would be 

> Error: Could not find or load main class Files

because of the default Windows folder name "Program Files".

**Comment by slandelle** [comment]
Fixed, thanks for reporting

**Comment by r-alukhanov** [comment]
Could you please merge the fix into 2.1 release?

**Comment by slandelle** [comment]
Next public release will be 2.2, planned for end of March.
