### ISSUE TITLE
Provide run description from maven plugin

### ISSUE THREAD

**Issue by mmartinsson** [gatling/gatling-maven#9]
The Gatling command line offers the user to provide a run description that shows up in the report. But if you use the Maven plugin that possibility is not available. It would be great if it was.

See pull request #8.

Updates to the documentation would also be needed to complete this issue. I offer to take care of that if the pull request is accepted.

**Comment by mmartinsson** [comment]
The configuration in the pom would look like this:

                ...
                <configuration>
                    ...
                    <runDescription>This-is-the-run-description</runDescription>
                </configuration>
                ...

**Comment by slandelle** [comment]
Closed by #8
